env:
  node: true
extends:
  - standard
  - plugin:import/recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - import
  - prettier
rules: 
  prettier/prettier: error
  no-extra-boolean-cast: off
  import/order:
    - error
    -
      alphabetize:
        order: asc
overrides:
  - 
    files:
      - "*/.ts"
    extends:
      - standard-with-typescript
      - plugin:import/typescript
    parserOptions:
      project:
        - ./tsconfig.node.json
    settings:
      import/resolver:
        typescript: true
    rules: 
      "@typescript-eslint/explicit-function-return-type": off
      "@typescript-eslint/triple-slash-reference": off
