root: true
env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - ./tsconfig.json
plugins:
  - react
  - react-hooks
  - import
  - prettier
settings:
  react:
    version: "detect"
  import/resolver:
    typescript: true
rules: 
  prettier/prettier: error
  no-extra-boolean-cast: off
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/triple-slash-reference": off
  "react/react-in-jsx-scope": off
  import/order:
    - error
    -
      alphabetize:
        order: asc
