root: true
env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - ./tsconfig.json
plugins:
  - react
  - react-hooks
  - import
  - prettier
settings:
  react:
    version: "detect"
  import/resolver:
    typescript:
      project: "./tsconfig.json"
rules: 
  prettier/prettier: error
  no-extra-boolean-cast: off
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/triple-slash-reference": off
  "@typescript-eslint/method-signature-style":
    - error
    - method
  "@typescript-eslint/no-confusing-void-expression":
    - error
    - 
      ignoreArrowShorthand: true
  react/react-in-jsx-scope: off
  react/prop-types: off
  react/no-unescaped-entities: off
  import/order:
    - error
    -
      # groups:
      #   - builtin
      #   - external
      #   - internal
      #   - parent
      #   - sibling
      #   - index
      # pathGroups:
      #   -
      #     pattern: "@/**/*"
      #     group: internal
      #     position: before
      #   -
      #     pattern: "@**/*"
      #     group: external
      #     position: after
      alphabetize:
        order: asc
